archive:
  archive_base_url: doc-archive
  archive_location: doc-archive
  force_download_base_url: https://raw.githubusercontent.com/ChanukaUOJ/gztarchiver-storage/test-v2-crawler
classification:
  enable: false
credentials:
  divert_deepseek_api_key: eyJ4NXQiOiJOaWk1WmNtcFlCNkZfbDJLWUVYYVdmQ3VGd3ciLCJraWQiOiJNVE0yWTJKak9UaGxaV1EwWW1WbU5qRmtPVFZqTkROa01HTTFZamRsTldFNU1qWXlaamMyWm1NNE1qbGlaRFkyWWpnd1l6ZGpZV0V4WVdNd1l6Tm1Nd19SUzI1NiIsInR5cCI6ImF0K2p3dCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI1SlFWeTh0ZjVJX3d4Um9iVHVtMnhqUldmb29hIiwiYXV0IjoiQVBQTElDQVRJT04iLCJpc3MiOiJodHRwczovL2FwaS5hc2dhcmRlby5pby90L2xhbmthZGF0YWZvdW5kYXRpb24vb2F1dGgyL3Rva2VuIiwiY2xpZW50X2lkIjoiNUpRVnk4dGY1SV93eFJvYlR1bTJ4alJXZm9vYSIsImF1ZCI6WyI1SlFWeTh0ZjVJX3d4Um9iVHVtMnhqUldmb29hIiwiY2hvcmVvOmRlcGxveW1lbnQ6cHJvZHVjdGlvbiJdLCJuYmYiOjE3ODgxOTY0MzcsImF6cCI6IjVKUVZ5OHRmNUlfd3hSb2JUdW0yeGpSV2Zvb2EiLCJvcmdfaWQiOiJhYWY4ZWNlMS0zMDc3LTRhNTItYWIwNS0xODNhNDI0ZjZkOTMiLCJleHAiOjE3ODgxOTczMzcsIm9yZ19uYW1lIjoibGFua2FkYXRhZm91bmRhdGlvbiIsImlhdCI6MTc4ODE5NjQzNywianRpIjoiMzY2OTVmNDUtNGRhYS00ZDRlLTg0NjAtYmZlNmQzYTYzMmY1Iiwib3JnX2hhbmRsZSI6ImxhbmthZGF0YWZvdW5kYXRpb24ifQ.swsmsITD_78MZmIvLN9zWxOpcWL6mosnOcQbmwdbrPeoFgROYwEruQqT-nsj4xiPjv0MVeqzSh3-VSuCBjfNQ9TJDGc9gQTBBt0J1pfP_r25t4IPRbRD4T7b2J0uX0f0PVFCATLEhpTkSDCxLWej_TRYbFu16SFRQw2wIAWZkJIzHTqzPjZfp1I9wORB53nr00mbrgnj7G95PX-V8xwahgruYdfwV3ygYcrX-VrjtyCQrdNexNLfwy7M1F_RV9BquhtgZzP22GBkmVA8EmJwPew1-NaQXByBPEYuRcyqzJ6BD0oAw22RlKqlJLNcnoGzvWtx7uMyIjgDz0gHuy1UCQ
  divert_url_deep_seek: your-deepseek-divert-url-from-bijira
output:
  doc_metadata_json: metadata/doc_metadata.json
  download_metadata_json: metadata/download_metadata.json
  log_classification: document_classification.csv
  log_failure: failed_to_archive.csv
  log_record_dir: records
  log_success: successfully_archived.csv
  log_unavailable: document_unavailable.csv
  metadata_dir: metadata
  years_json: metadata/years.json
scrape:
  url: https://documents.gov.lk/web/extra_gazettes
v2:
  api_endpoint: http://gvp-api:4500/website-data/extra-gazette/get-all
  cdn_proxy_url: https://documents.gov.lk/api/content-file-proxy?file=
  languages:
  - ENGLISH
  next_action_token: 7f679bcdf1c679caa0f2356b97387098c39c41312a
